projects:
  ChatAppAPI:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: oizw6kjwqrahznx5ubfs3mrjfm
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: ap-northeast-1
        maxDepth: 4
      endpoints:
        prod: >-
          https://qxmdtsfhwrb45kdwdcevpcrsky.appsync-api.ap-northeast-1.amazonaws.com/graphql
